### ISSUE TITLE
transloco-keys-manager don`t extract if "--project" provided with angular library

### ISSUE THREAD

**Issue by Alegiter** [ngneat/transloco-keys-manager#54]
First of all, thanks to transloco team)

Maybe I`m doing something wrong... But little tired looking for a solution. So I'm writing an issue request.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

In new angular project with generated library by `ng g library library-name`

Using command `transloco-keys-manager extract --project library-name`
Ouput: `Input undefined`

## Expected behavior

Using command `transloco-keys-manager extract --project library-name`
should extract key into assets folder of parent project or into assets folder of library-name

## Minimal reproduction of the problem with instructions

1. Generate new Angular project with `ng new project-name`
2. Generate library in it with `ng g library library-name`
3. Add transloco to project-name with `ng add @ngneat/transloco`
3.1 Answers for question: ru,en; no
4. Add transloco-key-manager to project-name with `ng g @ngneat/transloco:keys-manager`
5. Add script to project-name package.json `"i18n:extract:library-name": "transloco-keys-manager extract --project library-name"`
6. Run with `npm run i18n:extract:library-name`

## What is the motivation / use case for changing the behavior?

Using Transloco in Angular libraries and have the option to autoextract keys from it.

## Environment

<pre><code>
Angular version: 10.0.5

 
For Tooling issues:
- Node version: v12.18.1  
- Platform: Linux  

</code></pre>

**Comment by shaharkazaz** [comment]
@Alegiter
What happened here is that the default value for the input config is `['app']` and you wanted to extract from a lib has a root folder of `lib` the extraction failed due to invalid input.

In order to resolve this you can define a transloco config in your library folder with the correct input path.
I figured that this might be a coomon usecase so I did the following:
* The keys manager will now support OOTB libraries by checking the `projectType` in the `angular.json` and will set the correct default input path.
* For future issues like these I added the debugging section in the docs to help users understand how the keys manager configuration is resolved.

Please LMK if your issue is resolved in v2.6.0 🙂

**Comment by Alegiter** [comment]
@shaharkazaz 
Works like a charm! :smiley: 
And the new debugging feature is sooooo useful! Thank you very much!

**Comment by shaharkazaz** [comment]
@Alegiter Happy to hear! I hope to see you as a ngneat contributor in the future 😁
