### ISSUE TITLE
License for trans-loco-keys-manager

### ISSUE THREAD

**Issue by taylormathewson** [ngneat/transloco-keys-manager#67]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Maybe more a question than an issue, but I was wondering what license this particular package is offered under?  I don't see a license file in the repo.

For bg: where I work we put fair effort in trying to make sure we respect open source licenses, and this came up during a review.

Thanks to all involved for the great package!

**Comment by shaharkazaz** [comment]
@taylormathewson You are correct seems like the license is missing, I'll add it.
It's MIT 🙂

**Comment by taylormathewson** [comment]
Many thanks!

**Comment by rhuitl** [comment]
Thank you for sharing this project under the MIT license :-)

I have a question though because before your clarification @shaharkazaz, @NetanelBasal made an explicit statement in the file `regexs.ts` in 8ba70cb48e0d8f75e186e910df2e274a8ef5e738 about that particular code being proprietary. Not sure what the background was, maybe somebody was "stealing" the hard work that went into these regexes. But if the whole project should be made available unter the terms of the MIT, this disclaimer would have to be removed. 

@darkv has made a small addition to this file, as well, after the disclaimer had been introduced.

**Comment by shaharkazaz** [comment]
@rhuitl Thanks for pointing that out.
I'll update that file and release a new version.
