### ISSUE TITLE
Bug: EOF new line

### ISSUE THREAD

**Issue by ChazUK** [ngneat/transloco-keys-manager#79]
Running the extractor saves the files without a blank new line at the end of the file, which is a UNIX standard.

Expected:
Extracted files show be saved with an empty line at the end of the file.

**Comment by JustinPierce** [comment]
This is a constant annoyance for us, as we have Prettier set up to ensure that there is a newline at the end of every file. Since we have the extractor hooked up via Webpack, simply running our application for development causes an edit in every translation file. Sure, Prettier is going to wipe it out in the end, but it still looks like the key manager found keys to extract.

**Comment by shaharkazaz** [comment]
@JustinPierce @ChazUK You are welcome to open a PR 🙂 
I can't say any timeline for this issue due to a busy schedule.
